#!/bin/sh
[ 'bash' == $0 ] || [ ${BASH_SOURCE[0]} != $0 ] && {
  echo "Don't source this script! ${SELF}" >&2
  return
}
STARTD=${PWD}
GINHUB=${GINHUB:-'https://gist.github.com'}
GIN_NAME=${GIN_NAME:-gin}

SELFD=$(cd $(dirname $0) >/dev/null 2>&1; pwd)
SELF=$(basename $0)
[ -x ${SELFD}/${SELF} ] || {
  echo "Whoa! ${SELF}" >&2
  exit ${LINENO}
}
TYPE=${SELF##*.}
[ "${TYPE}" == "${SELF}" ] && TYPE=
SELF=${SELF%.*}
TEST=${TEST:-false}

gin_temp=

while :; do
  [ -d ${PWD}/.${GIN_NAME} ] && gin_temp="${gin_temp:+${gin_temp}:}${PWD}"
  [ ${PWD} == '/' ] && break
  cd .. >/dev/null 2>&1
done

cd "${STARTD}"

GIN_PATH="${gin_temp}${GIN_PATH:+:${GIN_PATH}}"

GIST=

OFS="${IFS}" IFS=':'
for gin in ${GIN_PATH}; do
  gin="${gin/[~]/${HOME}}"
  gin_dest="${gin}/.${GIN_NAME}"
  name="${gin_dest}/${SELF}"
  [ -L "${name}" ] && {
    GIST="${name}"
    break
  }
done
IFS="${OFS}"

[ "${GIST}" ] || {
  echo "${SELF} not found" >&2
  exit ${LINENO}
}

SCRIPT=$(\ls -l ${GIST} | awk '{print $NF}')
TYPE=${SCRIPT##*.}
[ "${TYPE}" == "${SCRIPT}" ] && {
  # TODO: cache script locally and just execute it.
  echo "${SCRIPT} unknown type" >&2
  exit ${LINENO}
}
CURL="curl -ks ${GINHUB}/${SCRIPT}"

${TEST} && printf "%s\n%s | " "${PWD}" "${CURL}"

[ 'sh' == ${TYPE} ] && {
  ${TEST} && echo "sh -s ${@}" || ${CURL} | sh -s ${@}
  exit $?
}

[ 'py' == ${TYPE} ] && {
  # TODO: support passing parameters to python.
  #       Will this mean writing the script to a tempfile? I think so.
  ${TEST} && echo "python" || ${CURL} | python
  exit $?
}

[ 'js' == ${TYPE} ] && {
  ${TEST} && echo "node" || ${CURL} | node
  exit $?
}

exit 1
